job1:
    script:
        - echo "job1 started.."
        - sleep 30
        -  hostname    
    tags:
        - docker

job2:
    script:
        - echo "job2  started.."
        - sleep 30
        -  hostname    
    tags:
        - shell